test/e2e: fix broken checkpoint tests
On main these tests fail right now due the parallel merge of commit
d01cd46830 ("test: remove outdated checkpoint skip") and commit
1b99ae56b0 ("New images 2026-04-24").

The new crun and/or criu versions in the CI images changed the error
message so adapt to that.

The new full error is:
Error: crun: (00.054135) Error (criu/cgroup.c:1998): cg: cgroupd: recv req error: No such file or directory: OCI runtime attempted to invoke a command that was not found

Signed-off-by: Paul Holzinger <pholzing@redhat.com>